config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/team', to:'gossips#team'
  get '/contact', to: 'gossips#contact'

  resources :gossips do
    resources :users, only: [:show]
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy, :show]

  resources :cities, only: [:show]

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	has_many :likes, as: :element_liked, dependent: :destroy
	has_many :bis_comments, class_name: "Comment", foreign_key: "main_comment_id"
	belongs_to :main_comment, class_name: "Comment", optional: true

	validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_current_user, only: [:edit, :update, :destroy]

  def new
    unless current_user
      redirect_to gossip_path(params[:gossip_id]), alert: "Please log in."
    end
    @new_comment = Comment.new(gossip_id:params[:gossip_id])
  end

  def create             
    @new_comment = Comment.new('gossip_id' => params[:gossip_id], 'content' => params[:comment_content])
    @new_comment.user = User.find_by(id: session[:user_id])
    # @gossip = Gossip.new('title' => params[:gossip_title], 'content' => params[:gossip_content])
    # @gossip.user = User.find_by(id: session[:user_id])
  
    if @new_comment.save
      redirect_to gossip_path(@new_comment.gossip_id), notice: "Le commentaire a bien été créé"
      puts 'Le commentaire a été créé !'
      
    else
      redirect_to new_gossip_comment_path, alert: "Certaines informations sont incorrectes : le commentaire ne peut être vide"
    end
  end

  def edit
    @this_comment = Comment.find(params[:id])
  end

  def update
    @this_comment = Comment.find(params[:id])
    @this_comment.update('content' => params[:comment_content])

    if @this_comment.save
      redirect_to gossip_path(@this_comment.gossip_id), notice: "Le commentaire a bien été modifié"
    
    else
      redirect_to this_gossip_comment_path, alert: "Certaines informations sont incorrectes : le commentaire ne peut être vide"
    end
  end

  def destroy
    @this_comment = Comment.find(params[:id])
    @this_comment.destroy
    redirect_to gossip_path(@this_comment.gossip_id), notice: "Ton commentaire a bien été supprimé"
  end

  def show
  end

  def index
  end

  private

  def authenticate_current_user
    unless current_user == Comment.find(params[:id]).user
      redirect_to gossip_path(params[:gossip_id]), alert: "Vous ne pouvez pas modifier ce commentaire"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<!doctype html>
<html>
    <head>
      <meta charset="utf-8" />
      <title>Éditer un commentaire</title>
    </head>
 
<body>

  <div class="row justify-content-sm-center">
    <div class="card" style="width: 18rem;">
      <h6 class="card-title mb-2 text-muted"><h5>Commentaire du potin :<%= @this_comment.gossip.title %></h5></h6>
      <p class="card-text"><%= @this_comment.gossip.content %></p>
    </div>
  </div>

  <br />
  <%= form_tag url_for(action: 'update'), method: "patch" do %>
    <div class="row justify-content-sm-center" >
      <%= label_tag 'Modifie ton commentaire :' %> <br />
      <br />
      <%= text_area_tag :comment_content %>
      <br />
    </div>
    <br />
    
    <div class="row justify-content-sm-center" >
      <%= submit_tag("Mettre à jour", :class =>"btn btn-outline-success btn-sm") %>
    </div>  
  <% end %>
    <br />
 
  <div class="row justify-content-sm-center">
    <a href="<%= gossip_comment_path(params[:gossip_id], params[:id])%>" class ="btn btn-outline-danger btn-sm" data-confirm="Etes-vous sûr ?" data-method="DELETE">Supprimer le commentaire ?</a>     
  </div> 
</body>
</html>

app/views/comments/new.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Créer un commentaire</title>
  </head>
 
  <body>
    <div class="row justify-content-md-center">
      <div class="col mb-4 text-center">

        <h1>Crée un commentaire pour le potin : <%= @new_comment.gossip.title%> </h1>
        <p>Balance ton potin via le formulaire ci-dessous</p>
        <br/>

        <%= form_tag url_for(action: 'create'), method: "post" do %>
          
          
          <%= label_tag 'Renseigne ton commentaire : ' %>
          <%= text_area_tag :comment_content %>
          <br/>

          <br />
          
          <%= submit_tag("Publier le commentaire", :class =>"btn btn-primary") %>

        <% end %>
      </div>
    </div>
  </body>
</html>