config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/team', to:'gossips#team'
  get '/contact', to: 'gossips#contact'

  resources :gossips do
    resources :users, only: [:show]
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy, :show]

  resources :cities, only: [:show]

end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :tags_in_gossips
	has_many :comments
	has_many :likes, as: :element_liked, dependent: :destroy
	has_many :tags, through: :tags_in_gossips

	validates :title, presence: true, length: { in: 3..30, message: "Un titre fait entre 3 et 14 caractères" }
	validates :content, presence: true
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  
  before_action :authenticate_current_user, only: [:edit, :update, :destroy]

	def team
  end

  def contact
  end

  def index
    @list_gossips = Gossip.all
  end

  def show
     @gossip_searched = Gossip.find(params[:id])
     @comments_linked = []
     Comment.all.each do |comment|
       if @gossip_searched.id == comment.gossip_id
        @comments_linked << comment
       end
     end
  end

  def new
    unless current_user
      redirect_to gossips_path, alert: "Please log in."
    end
  	@gossip = Gossip.new
  end

  def create 
    @gossip = Gossip.new('title' => params[:gossip_title], 'content' => params[:gossip_content])
    
    @gossip.user = current_user
                      
    if @gossip.save
      redirect_to gossips_path, notice: "Le potin #{@gossip.title} a bien été créé !"
    else
      redirect_to new_gossip_path, alert: "Certaines informations sont incorrectes : le titre doit faire entre 3 et 30 caractères"
    end    
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update('title'=> params[:gossip_title],'content'=> params[:gossip_content])
      redirect_to gossips_path , notice: "Ton gossip a bien été mis à jour"
    else
      redirect_to edit_gossip_path
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path, notice: "Ton gossip a bien été supprimé"
  end

  private

  def authenticate_current_user
    unless current_user == Gossip.find(params[:id]).user
      redirect_to gossip_path(params[:id]), alert: "Vous ne pouvez pas modifier ce potin"
    end
  end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/contact.html.erb
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>The Gossip Project - Contact</title>
    </head>

    <body>
       <center>  
       

        <p>
        <%= link_to("https://www.instagram.com/itsmeleighton/?hl=fr") do %>
              <div class="card-body">
              <button type="button" class="btn btn-success btn-lg btn-block"> 
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                  <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
        </svg> Contactez nous</button>
      </div>
      <%end%>
        </p> 
 
    <img src="https://image.freepik.com/vecteurs-libre/lettre-amour-design-plat_23-2147785126.jpg">
        </center>
    
    </body>
</html> 

app/views/gossips/edit.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Éditer un potin</title>
  </head>
 
  <body>
    <div class="row justify-content-md-center">
      <div class="col mb-4 text-center">

        <h1>Édite un potin </h1>
        <p>Modifie ton potin</p>
        <br/>

        <%= form_tag url_for(action: 'update'), method: "patch" do %>
          
          <%= label_tag 'Change le titre : ' %>
          <%= text_field_tag :gossip_title %>
          <br/>

          <%= label_tag 'Modifie ton potin : ' %>
          <%= text_area_tag :gossip_content %>
          <br/>

          <br />
          
          <%= submit_tag("Mettre à jour", :class =>"btn btn-success") %>

        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/gossips/index.html.erb
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>The Gossip Project - Home</title>
    </head>

    
  <body>
  
  <main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron" style="background-image: url(<%= 'https://news.ucr.edu/sites/g/files/rcwecm1816/files/styles/news_article_featured_l/public/2019-05/gossip%20pic.jpg' %>)"
    <div class="container">
      <h1 class="display-3">Welcome To The Best & Famous Gossip Project!</h1>
      <p>Bienvenue sur votre DASHBOARD. A vous la gloire!</p>
      <p><%= button_to "Crée un potin", new_gossip_path, class:"btn btn-primary btn-lg", :method => :get %></p>
    </div>
  </div>

  <center>
  <h1 style="font-size:40px;" >Tous les potins </h1>
  </br>

  

  
  <% @list_gossips.each do |gossip| %>
    <div class="card mb-4 box-shadow" style="width: 18rem;">
    <h5 class="card-title text-center">Potin n°<%= gossip.id %> </h5>
    <p class="card-text text-center">
        <%= link_to("/gossips/#{gossip.id}") do %>
            <%= gossip.user.pseudo %> : </br> <%= gossip.content %> </p>
        <% end %>	
        </div></br>
  <% end %>

  </body>
</center>  
</html>

app/views/gossips/new.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Créer un potin</title>
  </head>
 
  <body>
    <div class="row justify-content-md-center">
      <div class="col mb-4 text-center">

        <h1>Crée un potin !</h1>
        <p>Balance ton potin via le formulaire ci-dessous</p>
        <br/>

        <%= form_tag url_for(action: 'create'), method: "post" do %>
          
          <%= label_tag 'Renseigne un titre : ' %>
          <%= text_field_tag :gossip_title %>
          <br/>

          <%= label_tag 'Balance ton potin : ' %>
          <%= text_area_tag :gossip_content %>
          <br/>

          <br/>
          
          <%= submit_tag("Create Gossip", :class =>"btn btn-primary") %>

        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/gossips/show.html.erb
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>The Gossip Project - Gossip</title>
</head>

<body>

  <!-- Présentation potin-->
  <div class="row justify-content-md-center"> 
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h6 class="card-title mb-2 text-muted"><h1>Voici la page du potin n°<%= @gossip_searched.id %></h1></h6>
      <p class="card-text"><p> Titre : <%= @gossip_searched.title%> </p>
              
      <p>Son auteur :
        <%= link_to("#{@gossip_searched.id}/users/#{@gossip_searched.user_id}") do %> 
          <%=@gossip_searched.user.pseudo %>
        <% end %>
      </p>
    
      <p>Le contenu du potin : <%= @gossip_searched.content %></p>
      <p>Créé le : <%= @gossip_searched.created_at %></p>

    
      <p>Ville :
      <% if !@gossip_searched.user.city_id.nil? %>
        <%= link_to city_path(@gossip_searched.user.city_id) do %> 
          <%= @gossip_searched.user.city.name %>
        <% end %>
      <% end %>
      </p>

      <p><%= @gossip_searched.likes.count %> <%= (@gossip_searched.likes.count) == 1 ? 'Like' : 'Likes'%> 
        <% pre_like = @gossip_searched.likes.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
          <%= button_to 'Unlike', gossip_like_path(@gossip_searched, pre_like), method: :delete, class:"btn btn-danger" %>
        <% else %>
          <%= button_to 'Like', gossip_likes_path(@gossip_searched), method: :post, class:"btn btn-success" %>
        <% end %>
      </p>
    </div>

        

  <!-- Boutons gestion potin -->
    <div class="row justify-content-md-center mb-2">
      <a href="<%= new_gossip_comment_path(params[:id]) %>" class ="btn btn-primary">Commenter</a>     
    </div>
    </br>
    
    <% if @gossip_searched.user == current_user %>
      <div class="row justify-content-md-center m-2">
        <a href="<%= edit_gossip_path(params[:id]) %>" class ="btn btn-success">Mettre à jour le potin</a>     
      </div> 
            
      <div class="row justify-content-md-center m-2">
        <a href="<%= gossip_path(params[:id])%>" class ="btn btn-danger" data-confirm="Etes-vous sûr ?" data-method="DELETE">Supprimer le potin</a>     
      </div> 
      </br>
    <% end %>
    </div>
  </div>
  </br>
  </br>


  <!-- Commentaires -->
  <h3 class="text-center"> Voici la liste des commentaires </h3>
  </br>
  </br>
  <% @comments_linked.each do |comment| %>
    <div class="row justify-content-md-center">
      <p style="font-style: italic"> <%= comment.user.pseudo %> : <%= comment.content %></p>
    </div>
    
    <% if comment.user == current_user %>
      <div class="row justify-content-sm-center">
        <a href="<%= edit_gossip_comment_path(@gossip_searched.id, comment.id) %>" class ="btn btn-outline-success btn-sm">Mettre à jour le commentaire</a>  
      </div> 
      </br>
      <% end %>
  <% end %>
</body>
</html>

app/views/gossips/team.html.erb
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>The Gossip Project - Team</title>
    </head>

    <body>
    <div class='ml-5'>
      <br>
      <h2 class="text-center">Team Gossip Project</h2>
      <br>
        <div class="row justify-content-md-center">  
          <div class="col-lg-3 text-center">
            <img class = "square" src="https://media4.giphy.com/media/xT8qBnzRIMESUXqEgw/giphy.gif" class="rounded-sm" width="130" height="130" style="border-radius:50%"/>
            <h4>Fatouma</h4>
          </div>
 
          <div class="col-lg-3 text-center">
            <img class = "square" src="https://i.imgur.com/kEf0nMU.gif" class="rounded-sm" width="130" height="130" style="border-radius:50%"/>
            <h4>Clément</h4>
          </div>
          
          <div class="col-lg-3 text-center">
            <img class = "square" src="https://www.viedemerde.fr/img/6ec7fa87f019d710c7eed35f88612d89.gif/original/" class="rounded-sm" width="130" height="130" style="border-radius:50%"/>
            <h4>Caroline</h4>
          </div>

          <div class="col-lg-3 text-center">
            <img class = "square" src="https://media1.tenor.com/images/0062ebd0ed46176fafc0d84916c067e2/tenor.gif?itemid=13994717" class="rounded-sm" width="130" height="130" style="border-radius:50%"/>
            <h4>Halima</h4>
          </div>
        </div>
 
        <div class="row justify-content-md-center">  
          <div class="col-lg-3 text-center">
                <img class = "square" src="https://data.photofunky.net/output/image/0/e/9/b/0e9b77/photofunky.gif" class="rounded-sm" width="130" height="130" style="border-radius:50%"/>
              
                <h4>Camillia</h4>
            </div>

          <div class="col-lg-3 text-center">
              <img class = "square" src="https://thumbs.gfycat.com/NeglectedUniformEastrussiancoursinghounds-size_restricted.gif" class="rounded-sm" width="130" height="130" style="border-radius:50%"/>
              <h4>Ton</h4>
          </div>

        <div class="col-lg-3 text-center">
            <img class = "square" src="https://myfrenchcity.com/wp-content/uploads/2016/03/chiken.gif" class="rounded-sm" width="130" height="130" style="border-radius:50%"/>
            <h4>Abdeldjalil</h4>
        </div>

        <div class="col-lg-3 text-center">
            <img class = "square" src="https://media.tenor.com/images/60b276ab00e136235854b2f72a6db9a5/tenor.gif" class="rounded-sm" width="130" height="130" style="border-radius:50%"/>
            <h4>Theo</h4>
        </div>
        
      </div>
    </div>
    </body>
</html>