config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/team', to:'gossips#team'
  get '/contact', to: 'gossips#contact'

  resources :gossips do
    resources :users, only: [:show]
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy, :show]

  resources :cities, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :gossips, through: :users
	validates :name, presence: true
	validates :zip_code, presence: true, length: {is: 5}

	def self.exists(this_city_name)
		!City.find_by(name: this_city_name).nil?
	end

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	has_many :likes, as: :element_liked, dependent: :destroy
	has_many :bis_comments, class_name: "Comment", foreign_key: "main_comment_id"
	belongs_to :main_comment, class_name: "Comment", optional: true

	validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :tags_in_gossips
	has_many :comments
	has_many :likes, as: :element_liked, dependent: :destroy
	has_many :tags, through: :tags_in_gossips

	validates :title, presence: true, length: { in: 3..30, message: "Un titre fait entre 3 et 14 caractères" }
	validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :element_liked, polymorphic:true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
    
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tags_in_gossips
	has_many :gossips, through: :tags_in_gossips

	validates :title, presence: true, length: { in: 3..14, message: "Un tag fait entre 3 et 14 caractères" }
end

app/models/tags_in_gossip.rb
class TagsInGossip < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
	belongs_to :city, optional: true
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments
  has_many :likes, dependent: :destroy

  has_secure_password

 
  validates :pseudo, presence: true, uniqueness: true
  validates :first_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :last_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 3 }

  include BCrypt

  def password_authentification(mdp_confirmation, user)
    
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    def show
        @city_searched = City.find(params[:id])
        @list_gossips = Gossip.all
        
        @list_gossips_this_city = []
        
        @list_gossips.each do |gossip|
            if @city_searched.id == gossip.user.city_id
                @list_gossips_this_city << gossip
            end
        end

    end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  
  before_action :authenticate_current_user, only: [:edit, :update, :destroy]

	def team
  end

  def contact
  end

  def index
    @list_gossips = Gossip.all
  end

  def show
     @gossip_searched = Gossip.find(params[:id])
     @comments_linked = []
     Comment.all.each do |comment|
       if @gossip_searched.id == comment.gossip_id
        @comments_linked << comment
       end
     end
  end

  def new
    unless current_user
      redirect_to gossips_path, alert: "Please log in."
    end
  	@gossip = Gossip.new
  end

  def create 
    @gossip = Gossip.new('title' => params[:gossip_title], 'content' => params[:gossip_content])
    
    @gossip.user = current_user
                      
    if @gossip.save
      redirect_to gossips_path, notice: "Le potin #{@gossip.title} a bien été créé !"
    else
      redirect_to new_gossip_path, alert: "Certaines informations sont incorrectes : le titre doit faire entre 3 et 30 caractères"
    end    
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update('title'=> params[:gossip_title],'content'=> params[:gossip_content])
      redirect_to gossips_path , notice: "Ton gossip a bien été mis à jour"
    else
      redirect_to edit_gossip_path
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path, notice: "Ton gossip a bien été supprimé"
  end

  private

  def authenticate_current_user
    unless current_user == Gossip.find(params[:id]).user
      redirect_to gossip_path(params[:id]), alert: "Vous ne pouvez pas modifier ce potin"
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_gossip
    before_action :find_like, only: [:destroy]

  def create
    if already_liked?
        flash[:alert] = "Tu ne peux pas liker plus d'une fois"
    else
        @gossip.likes.create(user_id: current_user.id, element_liked_type: "Gossip", element_liked_id:@gossip.id)
    end
    redirect_to gossip_path(@gossip.id)
  end

  def destroy
    if !(already_liked?)
      flash[:alert] = "Tu ne peux pas desaimer ce potin"
    else
      @like.destroy
    end
    redirect_to gossip_path(@gossip)
  end

  private
  
  def find_gossip
    @gossip = Gossip.find(params[:gossip_id])
  end

  def find_like
    @like = @gossip.likes.find(params[:id])
 end

  def already_liked?
    Like.where(user_id: current_user.id, element_liked_id: params[:gossip_id], element_liked_type: "Gossip").exists?
  end
end

app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController
	include BCrypt

	def new
		@new_user = User.new
	end

	def create
		if params[:user_password] == params[:user_authentification]
			@new_user = User.new('first_name' => params[:user_first_name],'last_name' => params[:user_last_name],'pseudo' => params[:user_pseudo],'email' => params[:user_email],'password' => params[:user_password],'description' => params[:user_description],'age' => params[:user_age].to_i)
			
			if @new_user.save
				redirect_to gossips_path, notice: "Le profil a bien été créé"
				log_in(@new_user)
				puts "le profil est connecté"
			else
				redirect_to new_user_path, alert: "Certaines informations sont incorrectes : Veuillez saisir tous les champs"
			end
		
			@new_user = User.update('city_id' => City.find_by(name: params[:user_city]).id) if !City.find_by(name: params[:user_city]).nil?
		
		else
			redirect_to new_user_path, alert: "Erreur, les deux mots de passe ne sont pas les mêmes"
		end
	end

	def show
		@user_searched = User.find(params[:id]) 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/session_helper.rb
module SessionHelper
    def current_user
      User.find_by(id: session[:user_id])
    end
 
    def log_in(user)
      session[:user_id] = user.id
    end
 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <span class="navbar-brand"><%= link_to "Gossip Project", gossips_path %></span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <span class="nav-link"><%= link_to "Team", team_path %></span>
          </li>
          <li class="nav-item">
            <span class="nav-link"><%= link_to "Contact", contact_path %></span>
          </li>
          
          <li class="dropdown"style="margin-left: 5px; margin-bottom: 3px;">
                <a class="btn btn-primary btn-rounded btn-sm dropdown-toggle"  href="#"  data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login / Log-out <span class="caret"></span></a>
                <ul class="dropdown-menu"	>
                  <% if current_user %>
                    <li><%= link_to "Se déconnecter", session_path(current_user.id), method: :delete %></li>
                  <% else %>
                    <li><%= link_to "S'inscrire",  new_user_path %></li>
                    <li><%= link_to 'Se connecter', new_session_path %></li>
                  <% end %>
                </ul>
              </li>
             
        </ul>
      </div>
    </nav>

    <% flash.each do |type, msg| %>
      <% case type %>
        <% when "notice" %>
          <div class="alert alert-success">
            <%= msg %>
          </div>
        <% when "alert" %>
          <div class="alert alert-danger">
            <%= msg %>
          </div>
      <% end %>
    <% end %>
  
    <%= yield %>

  <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  
  </body>
</html>